import express from "express";
import * as controllers from "./environment-setup-controllers";

const router = express.Router();

router.post("/ramblers/groups-by-area", controllers.groupsByArea);
router.post("/ramblers/group-details", controllers.groupDetailsRequest);
router.post("/ramblers/validate-api-key", controllers.validateRamblersApiKeyRequest);
router.post("/validate/mongodb", controllers.validateMongoDb);
router.post("/validate/aws-admin", controllers.validateAwsAdmin);
router.post("/validate/request", controllers.validateEnvironmentRequest);
router.post("/create", controllers.createEnvironmentRequest);
router.get("/session/:sessionId", controllers.sessionDetails);
router.get("/sessions", controllers.sessionsDetails);
router.get("/status", controllers.setupStatus);
router.post("/sync-ngx-lite", controllers.syncNgxLite);
router.get("/defaults", controllers.requireSetupAccess, controllers.environmentDefaults);
router.get("/environment-details/:environmentName", controllers.requireSetupAccess, controllers.environmentDetailsRequest);
router.get("/environment-status/:environmentName", controllers.environmentStatus);
router.get("/hostname-status/:environmentName", controllers.requireSetupAccess, controllers.hostnameHealth);
router.get("/send-control/:environmentName", controllers.requireSetupAccess, controllers.environmentSendControl);
router.post("/send-control/:environmentName", controllers.requireSetupAccess, controllers.updateEnvironmentSendControl);
router.post("/site-url/:environmentName", controllers.updateSiteUrl);
router.get("/existing-environments", controllers.existingEnvironments);
router.post("/fly-org-migration-status/:environmentName", controllers.flyOrganisationMigrationStatus);
router.get("/mongo-clusters", controllers.mongoClusters);
router.post("/resume", controllers.resumeEnvironmentRequest);
router.delete("/destroy/:environmentName", controllers.destroyEnvironmentRequest);
router.post("/copy-assets/:environmentName", controllers.copyAssetsRequest);
router.post("/setup-subdomain/:environmentName", controllers.setupSubdomainRequest);
router.post("/remove-subdomain/:environmentName", controllers.removeSubdomainRequest);
router.post("/probe-custom-domain/:environmentName", controllers.requireSetupAccess, controllers.probeCustomDomain);
router.post("/add-custom-domain/:environmentName", controllers.addCustomDomainRequest);
router.post("/remove-custom-domain/:environmentName", controllers.removeCustomDomainRequest);
router.post("/check-custom-domain/:environmentName", controllers.checkCustomDomainRequest);
router.post("/setup-apex-redirect/:environmentName", controllers.setupApexRedirectRequest);
router.post("/remove-apex-redirect/:environmentName", controllers.removeApexRedirectRequest);
router.post("/authenticate-brevo-domain/:environmentName", controllers.authenticateBrevoDomainRequest);
router.post("/move-mail-to-custom-domain/:environmentName", controllers.moveMailToCustomDomainRequest);
router.post("/enable-inbound-mail/:environmentName", controllers.requireSetupAccess, controllers.enableInboundMailRequest);
router.post("/seed-sample-pages/:environmentName", controllers.seedSamplePagesRequest);
router.post("/seed-notification-configs/:environmentName", controllers.seedNotificationConfigsRequest);
router.post("/admin-password-reset/:environmentName", controllers.adminPasswordResetRequest);
router.get("/schema-exists", controllers.schemaExists);
router.get("/estate-rebuild-capture/inventory", controllers.requireSetupAccess, controllers.estateRebuildCaptureInventory);
router.get("/estate-rebuild-capture/summary", controllers.requireSetupAccess, controllers.estateRebuildCaptureSummary);
router.get("/estate-rebuild-capture", controllers.requireSetupAccess, controllers.downloadEstateRebuildCapture);
router.get("/console-access/environments", controllers.requireSetupAccess, controllers.listConsoleAccessEnvironments);
router.get("/console-access", controllers.requireSetupAccess, controllers.getConsoleAccess);
router.put("/console-access", controllers.requireSetupAccess, controllers.saveConsoleAccess);
router.post("/contributor-bundle", controllers.contributorBundleRequest);

export const environmentSetupRoutes = router;
