import express from "express";
import { sendTransactionalMail } from "./transactional-mail/send-transactional-mail";
import { batchTransactionalStatus, cancelBatchTransactional, startBatchTransactionalSend } from "./transactional-mail/batch-transactional-send";
import { sendForgotPasswordEmail } from "./transactional-mail/send-forgot-password-email";
import { resolveTrackingUrl } from "./transactional-mail/resolve-tracking-url";
import { queryAccount } from "./account/account";
import { queryTemplates } from "./templates/query-templates";
import { listCreate } from "./lists/list-create";
import { lists } from "./lists/lists";
import { contactsCreate } from "./contacts/contacts-create";
import { attributes } from "./contacts/contact-attributes";
import { contacts } from "./contacts/contacts";
import { contactInfo } from "./contacts/contact-info";
import { contactCampaignStats } from "./contacts/contact-campaign-stats";
import { contactEvents } from "./contacts/contact-events";
import { transactionalEmailsList } from "./transactional-mail/transactional-emails-list";
import { transactionalEmailContent } from "./transactional-mail/transactional-email-content";
import { transactionalAggregatedReport } from "./transactional-mail/transactional-aggregated-report";
import { contactUpdate } from "./contacts/contact-update";
import { contactsInList } from "./contacts/contacts-in-list";
import { contactsRemoveFromList } from "./contacts/contacts-remove-from-list";
import { contactsAddToList } from "./contacts/contacts-add-to-list";
import { folders } from "./folders/folders";
import { listDelete } from "./lists/list-delete";
import { contactsBatchUpdate } from "./contacts/contacts-batch-update";
import { contactsDelete } from "./contacts/contact-delete";
import { getBrevoContactSnapshot } from "./contacts/contact-snapshot";
import { clearAllBlocklist, removeFromBlocklist, unsubscribeActivity, unsubscribeHistory, unsubscribes } from "./contacts/unsubscribes";
import { confirmUnsubscribe, decodeUnsubscribeRequest, redirectFromList, submitUnsubscribeFeedback } from "./contacts/branded-unsubscribe";
import { brevoEventsWebhook, brevoEventsWebhookConfig } from "./brevo-events-webhook";
import { sendCampaign } from "./campaigns/send-campaign";
import { createCampaign } from "./campaigns/create-campaign";
import { queryCampaigns } from "./campaigns/query-campaigns";
import { campaignContent } from "./campaigns/campaign-content";
import { campaignStats } from "./campaigns/campaign-stats";
import { campaignRecipients } from "./campaigns/campaign-recipients";
import { cancelCampaignRoute, queueSummaryRoute, releaseCampaignRoute } from "./campaigns/campaign-queue";
import { querySegments } from "./segments/query-segements";
import { senders } from "./senders/senders";
import { createSender } from "./senders/create-sender";
import { deleteSender } from "./senders/delete-sender";
import { updateSender } from "./senders/update-sender";
import { listUpdate } from "./lists/list-update";
import { listSubscriptionsExport } from "./lists/list-subscriptions-export";
import { listSubscriptionsParse } from "./lists/list-subscriptions-parse";
import { receiveFileUpload } from "../aws/file-upload";
import { templateDiff } from "./templates/template-diff";
import { renderTemplatePreview } from "./templates/render-template-preview";
import { localTemplateContent, localTemplateNamesList } from "./templates/local-template-content";
import { editableBodyContent } from "./templates/editable-body";
import { domainsList } from "./domains/domains-list";
import { registerDomainRoute } from "./domains/register-domain";
import { domainConfigRoute } from "./domains/domain-config";
import { authenticateDomainRoute } from "./domains/authenticate-domain-route";
import { switchDomainRoute } from "./domains/switch-domain-route";
import { deleteDomainRoute } from "./domains/delete-domain";
import * as authConfig from "../auth/auth-config";

const router = express.Router();

router.get("/folders", folders);
router.get("/contacts", contacts);
router.get("/contacts/list", contactsInList);
router.post("/contacts/delete", authConfig.authenticate(), contactsDelete);
router.post("/contacts/create", authConfig.authenticate(), contactsCreate);
router.post("/contacts/batch-update", authConfig.authenticate(), contactsBatchUpdate);
router.post("/contacts/add-to-list", authConfig.authenticate(), contactsAddToList);
router.post("/contacts/remove-from-list", authConfig.authenticate(), contactsRemoveFromList);
router.post("/contacts/update", authConfig.authenticate(), contactUpdate);
router.get("/contacts/attributes", authConfig.authenticate(), attributes);
router.get("/contacts/:identifier/info", authConfig.authenticate(), contactInfo);
router.get("/contacts/:identifier/campaign-stats", authConfig.authenticate(), contactCampaignStats);
router.get("/contacts/:identifier/events", authConfig.authenticate(), contactEvents);
router.get("/contacts/:identifier/snapshot", authConfig.authenticate(), getBrevoContactSnapshot);
router.get("/transactional/emails", authConfig.authenticate(), transactionalEmailsList);
router.get("/transactional/emails/:uuid/content", authConfig.authenticate(), transactionalEmailContent);
router.get("/transactional/aggregated-report", authConfig.authenticate(), transactionalAggregatedReport);
router.get("/unsubscribes", authConfig.authenticate(), unsubscribes);
router.get("/unsubscribes/activity", authConfig.authenticate(), unsubscribeActivity);
router.get("/unsubscribes/history", authConfig.authenticate(), unsubscribeHistory);
router.delete("/unsubscribes", authConfig.authenticate(), clearAllBlocklist);
router.delete("/unsubscribes/:email", authConfig.authenticate(), removeFromBlocklist);
router.get("/unsubscribe/decode", decodeUnsubscribeRequest);
router.post("/unsubscribe/confirm", confirmUnsubscribe);
router.post("/unsubscribe/feedback", submitUnsubscribeFeedback);
router.get("/unsubscribe/from-list", redirectFromList);
router.post("/webhooks/brevo-events", brevoEventsWebhook);
router.get("/webhooks/brevo-events/config", authConfig.authenticate(), brevoEventsWebhookConfig);
router.get("/senders", authConfig.authenticate(), senders);
router.post("/senders/create", authConfig.authenticate(), createSender);
router.put("/senders/:senderId", authConfig.authenticate(), updateSender);
router.delete("/senders/:senderId", authConfig.authenticate(), deleteSender);
router.post("/transactional/send", authConfig.authenticate(), sendTransactionalMail);
router.post("/transactional/batch/start", authConfig.authenticate(), startBatchTransactionalSend);
router.get("/transactional/batch/:jobId", authConfig.authenticate(), batchTransactionalStatus);
router.post("/transactional/batch/:jobId/cancel", authConfig.authenticate(), cancelBatchTransactional);
router.post("/transactional/forgot-password", sendForgotPasswordEmail);
router.post("/transactional/resolve-tracking-url", authConfig.authenticate(), resolveTrackingUrl);
router.post("/campaign/create", authConfig.authenticate(), createCampaign);
router.post("/campaign/send", authConfig.authenticate(), sendCampaign);
router.get("/campaigns", authConfig.authenticate(), queryCampaigns);
router.get("/campaigns/:campaignId/content", authConfig.authenticate(), campaignContent);
router.get("/campaigns/:campaignId/stats", authConfig.authenticate(), campaignStats);
router.get("/campaigns/:campaignId/recipients", authConfig.authenticate(), campaignRecipients);
router.get("/campaign/queue", authConfig.authenticate(), queueSummaryRoute);
router.post("/campaign/:campaignId/release", authConfig.authenticate(), releaseCampaignRoute);
router.post("/campaign/:campaignId/cancel", authConfig.authenticate(), cancelCampaignRoute);
router.get("/segments", authConfig.authenticate(), querySegments);
router.post("/templates", queryTemplates);
router.post("/templates/diff", authConfig.authenticate(), templateDiff);
router.post("/templates/local-content", authConfig.authenticate(), localTemplateContent);
router.get("/templates/local-names", authConfig.authenticate(), localTemplateNamesList);
router.post("/templates/editable-body", authConfig.authenticate(), editableBodyContent);
router.post("/templates/render", authConfig.authenticate(), renderTemplatePreview);
router.get("/lists", lists);
router.delete("/lists/delete", authConfig.authenticate(), listDelete);
router.post("/lists/create", authConfig.authenticate(), listCreate);
router.post("/lists/update", authConfig.authenticate(), listUpdate);
router.post("/lists/subscriptions/export", authConfig.authenticate(), listSubscriptionsExport);
router.post("/lists/subscriptions/parse", authConfig.authenticate(), receiveFileUpload, listSubscriptionsParse);
router.get("/account", queryAccount);
router.get("/domains", authConfig.authenticate(), domainsList);
router.post("/domains/register", authConfig.authenticate(), registerDomainRoute);
router.get("/domains/configuration", authConfig.authenticate(), domainConfigRoute);
router.post("/domains/authenticate", authConfig.authenticate(), authenticateDomainRoute);
router.post("/domains/switch", authConfig.authenticate(), switchDomainRoute);
router.delete("/domains/delete", authConfig.authenticate(), deleteDomainRoute);
export const brevoRoutes = router;
