app = "ngx-ramblers-jitsi"
primary_region = "lhr"

[build]
  dockerfile = "jitsi/Dockerfile"

[env]
  TZ = "Europe/London"
  ENABLE_AUTH = "1"
  ENABLE_GUESTS = "0"
  AUTH_TYPE = "jwt"
  ENABLE_AUTO_OWNER = "0"

[http_service]
  internal_port = 80
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0

[[services]]
  protocol = "udp"
  internal_port = 10000

  [[services.ports]]
    port = 10000

[[vm]]
  size = "performance-2x"
  memory = "4gb"
