import { composeInboxReply } from "./inbox-reply-controllers";
import express from "express";
import * as authConfig from "../auth/auth-config";
import { sendCalendarReply } from "./inbox-calendar-reply";
import { handleUnassignedCommitteeRoles } from "./inbox-unassigned-roles-controller";
import { permanentlyDeleteSelectedThreads } from "./inbox-delete-controller";
import { listMailboxConnections, createMailboxConnection, deleteMailboxConnection, updateMailboxAccessMode, updateMailboxImportAll, rescanGeneralMailbox, updateMailboxSyncMode, syncMailboxConnection } from "./inbox-connections-controllers";
import { readPubsubPushConfig, receivePubsubPush, readPushPublicKey, subscribeInboxPush, unsubscribeInboxPush } from "./inbox-push-controllers";
import { listInboxAliases, readJunkAccess, updateRoleNotifications, updateRoleNotificationEmail, updateAliasNotifications } from "./inbox-aliases-controllers";
import { readInboxUnreadCounts, listInboxThreads } from "./inbox-thread-list-controllers";
import { createInboxFolder, deleteInboxFolder, listInboxFolders, moveThreadsToUserFolder, renameInboxFolder } from "./inbox-folders-controllers";
import { readInboxThread, markThreadRead, markThreadUnread, deleteInboxThread, restoreInboxThread, moveThreadToInbox } from "./inbox-thread-actions-controllers";
import { listOrphanedThreads, remapOrphanedThreads, restoreOrphanedThreads } from "./inbox-repair-controllers";

const router = express.Router();

router.get("/mailbox-connections", authConfig.authenticate(), listMailboxConnections);
router.post("/mailbox-connections", authConfig.authenticate(), createMailboxConnection);
router.delete("/mailbox-connections/:id", authConfig.authenticate(), deleteMailboxConnection);
router.put("/mailbox-connections/:id/access-mode", authConfig.authenticate(), updateMailboxAccessMode);
router.put("/mailbox-connections/:id/import-all", authConfig.authenticate(), updateMailboxImportAll);
router.post("/mailbox-connections/:id/rescan-general", authConfig.authenticate(), rescanGeneralMailbox);
router.put("/mailbox-connections/:id/sync-mode", authConfig.authenticate(), updateMailboxSyncMode);
router.get("/pubsub/push-config", authConfig.authenticate(), readPubsubPushConfig);
router.post("/pubsub/push", receivePubsubPush);
router.get("/push/vapid-public-key", authConfig.authenticate(), readPushPublicKey);
router.post("/push/subscriptions", authConfig.authenticate(), subscribeInboxPush);
router.delete("/push/subscriptions", authConfig.authenticate(), unsubscribeInboxPush);
router.get("/aliases", authConfig.authenticate(), listInboxAliases);
router.get("/junk-access", authConfig.authenticate(), readJunkAccess);
router.put("/aliases/:roleType/notifications", authConfig.authenticate(), updateRoleNotifications);
router.put("/aliases/:roleType/notification-email", authConfig.authenticate(), updateRoleNotificationEmail);
router.put("/aliases/notifications", authConfig.authenticate(), updateAliasNotifications);
router.get("/unread-counts", authConfig.authenticate(), readInboxUnreadCounts);
router.get("/folders", authConfig.authenticate(), listInboxFolders);
router.post("/folders", authConfig.authenticate(), createInboxFolder);
router.put("/folders/:id", authConfig.authenticate(), renameInboxFolder);
router.delete("/folders/:id", authConfig.authenticate(), deleteInboxFolder);
router.post("/threads/move", authConfig.authenticate(), moveThreadsToUserFolder);
router.get("/threads", authConfig.authenticate(), listInboxThreads);
router.get("/unassigned-roles", authConfig.authenticate(), handleUnassignedCommitteeRoles);
router.get("/orphaned-threads", authConfig.authenticate(), listOrphanedThreads);
router.post("/orphaned-threads/remap", authConfig.authenticate(), remapOrphanedThreads);
router.post("/orphaned-threads/restore-to-inbox", authConfig.authenticate(), restoreOrphanedThreads);
router.post("/threads/delete", authConfig.authenticate(), permanentlyDeleteSelectedThreads);
router.get("/threads/:id", authConfig.authenticate(), readInboxThread);
router.post("/threads/:id/mark-read", authConfig.authenticate(), markThreadRead);
router.post("/threads/:id/mark-unread", authConfig.authenticate(), markThreadUnread);
router.post("/threads/:id/calendar-reply", authConfig.authenticate(), sendCalendarReply);
router.post("/threads/:id/compose-reply", authConfig.authenticate(), composeInboxReply);
router.delete("/threads/:id", authConfig.authenticate(), deleteInboxThread);
router.post("/threads/:id/restore", authConfig.authenticate(), restoreInboxThread);
router.post("/threads/:id/move-to-inbox", authConfig.authenticate(), moveThreadToInbox);
router.post("/mailbox-connections/:id/sync", authConfig.authenticate(), syncMailboxConnection);

export const inboxRoutes = router;
