#!/usr/bin/env bash
export NODE_ENV=dev
export MONGODB_URI=123
export AWS_REGION=123
export AWS_BUCKET=123
export AUTH_SECRET=123
export AWS_ACCESS_KEY_ID=123
export AWS_SECRET_ACCESS_KEY=123
export GOOGLE_MAPS_APIKEY=123
export MONGOLAB_APIKEY=123
export MEETUP_ACCESS_TOKEN=123
export INSTAGRAM_ACCESS_TOKEN=123
export INSTAGRAM_USER_ID=123
export INSTAGRAM_CLIENT_ID=123
export INSTAGRAM_CLIENT_SECRET=123
export CHROME_BIN="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
export DEBUG_COLORS=true
export DEBUG=ekwg:*
