import {
  WalkNotificationFieldDescriptor,
  WalkNotificationValueFormat as Format
} from "./walk-notification-field.model";
import { EventField, GroupEventField } from "./walk.model";

export const WALK_NOTIFICATION_FIELDS: Record<string, WalkNotificationFieldDescriptor> = {
  [EventField.ATTACHMENT]: {label: "Attachment", notify: true, format: Format.FILE},
  [EventField.ATTENDEES]: {label: "Attendance", notify: true, format: Format.ATTENDEES},
  [EventField.GPX_FILE]: {label: "Route file", notify: true, format: Format.FILE},
  [EventField.CONTACT_DETAILS]: {label: "Leader contact details", notify: true, format: Format.CONTACT_DETAILS},
  [EventField.IMAGE_CONFIG]: {label: "Image source", notify: true, format: Format.IMAGE_CONFIG},
  [EventField.LINKS]: {label: "Related links", notify: true, format: Format.LINKS},
  [EventField.MEETUP]: {label: "Meetup settings", notify: true, format: Format.MEETUP},
  [EventField.MILES_PER_HOUR]: {label: "Expected walking speed", notify: true, format: Format.SPEED},
  [EventField.PUBLISHING]: {label: "Publishing", notify: true, format: Format.PUBLISHING},
  [EventField.RISK_ASSESSMENT]: {label: "Risk assessment", notify: true, format: Format.RISK_ASSESSMENT},
  [EventField.VENUE]: {label: "Venue", notify: true, format: Format.VENUE},
  [GroupEventField.ACCESSIBILITY]: {label: "Accessibility", notify: true, format: Format.METADATA},
  [GroupEventField.ADDITIONAL_DETAILS]: {label: "Additional details", notify: true, format: Format.MARKDOWN},
  [GroupEventField.AREA_CODE]: {label: "Area code", notify: true, format: Format.TEXT},
  [GroupEventField.ASCENT_FEET]: {label: "Ascent in feet", notify: true, format: Format.TEXT},
  [GroupEventField.ASCENT_METRES]: {label: "Ascent in metres", notify: true, format: Format.TEXT},
  [GroupEventField.CANCELLATION_REASON]: {label: "Cancellation reason", notify: true, format: Format.TEXT},
  [GroupEventField.DATE_CREATED]: {label: "Date created", notify: false, format: Format.DATE_TIME},
  [GroupEventField.DATE_UPDATED]: {label: "Date updated", notify: false, format: Format.DATE_TIME},
  [GroupEventField.DESCRIPTION]: {label: "Walk description", notify: true, format: Format.MARKDOWN},
  [GroupEventField.DIFFICULTY]: {label: "Grade", notify: true, format: Format.METADATA},
  [GroupEventField.DISTANCE_KM]: {label: "Distance in kilometres", notify: true, format: Format.TEXT},
  [GroupEventField.DISTANCE_MILES]: {label: "Distance in miles", notify: true, format: Format.TEXT},
  [GroupEventField.DURATION]: {label: "Duration", notify: true, format: Format.TEXT},
  [GroupEventField.END_DATE_TIME]: {label: "End date & time", notify: true, format: Format.DATE_TIME},
  [GroupEventField.END_LOCATION]: {label: "End location", notify: true, format: Format.LOCATION},
  [GroupEventField.EVENT_ORGANISER]: {label: "Event organiser", notify: true, format: Format.CONTACT},
  [GroupEventField.EXTERNAL_URL]: {label: "External link", notify: true, format: Format.TEXT},
  [GroupEventField.FACILITIES]: {label: "Facilities", notify: true, format: Format.METADATA},
  [GroupEventField.GROUP_CODE]: {label: "Group code", notify: false, format: Format.TEXT},
  [GroupEventField.GROUP_NAME]: {label: "Group name", notify: true, format: Format.TEXT},
  [GroupEventField.ITEM_TYPE]: {label: "Event type", notify: true, format: Format.TEXT},
  [GroupEventField.LINKED_EVENT]: {label: "Linked event", notify: true, format: Format.TEXT},
  [GroupEventField.LOCATION]: {label: "Location", notify: true, format: Format.LOCATION},
  [GroupEventField.MEDIA]: {label: "Walk images", notify: true, format: Format.MEDIA},
  [GroupEventField.MEETING_DATE_TIME]: {label: "Meeting date & time", notify: true, format: Format.DATE_TIME},
  [GroupEventField.MEETING_LOCATION]: {label: "Meeting location", notify: true, format: Format.LOCATION},
  [GroupEventField.SHAPE]: {label: "Route type", notify: true, format: Format.TEXT},
  [GroupEventField.START_DATE]: {label: "Start date & time", notify: true, format: Format.DATE_TIME},
  [GroupEventField.START_LOCATION]: {label: "Starting location", notify: true, format: Format.LOCATION},
  [GroupEventField.STATUS]: {label: "Status", notify: true, format: Format.TEXT},
  [GroupEventField.TITLE]: {label: "Title", notify: true, format: Format.TEXT},
  [GroupEventField.TRANSPORT]: {label: "Transport", notify: true, format: Format.METADATA},
  [GroupEventField.URL]: {label: "Ramblers link", notify: false, format: Format.TEXT},
  [GroupEventField.WALK_LEADER]: {label: "Walk leader", notify: true, format: Format.CONTACT}
};
