name: Deploy and Build Docker Image and release to Heroku

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ngx-ramblers:latest
      - name: Tag the Docker image
        run: docker tag ngx-ramblers:latest ${{ secrets.DOCKER_USERNAME }}/ngx-ramblers:latest
      - name: Push the Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ngx-ramblers:latest
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
      - name: Log in to Heroku container registry
        run: |
          echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username="${{ secrets.HEROKU_EMAIL }}" --password-stdin registry.heroku.com
      - name: Pull Docker image from Docker Hub
        run: |
          docker pull nbarrett36/ngx-ramblers:latest
      - name: Tag Docker image for Heroku
        run: |
          docker tag nbarrett36/ngx-ramblers:latest registry.heroku.com/ngx-ramblers-docker/latest
      - name: Push Docker image to Heroku
        run: |
          docker push registry.heroku.com/ngx-ramblers-docker/latest
      - name: Release Docker image on Heroku
        run: |
          heroku container:release latest --app ngx-ramblers-docker
